// rtl/verilog/fp16/reciprocal_lut_16b.v
//======================================================================
//
// WARNING: THIS MODULE IS AUTO-GENERATED BY generate_lut.py.
//          DO NOT EDIT THIS MODULE MANUALLY.
//          MANUAL EDITS WILL BE OVERWRITTEN ON THE NEXT SCRIPT RUN.
//
//======================================================================
// Verilog RTL Generated by generate_lut.py
// LUT for fp16 reciprocal initial guess.
// Function: 1/M
// M is constructed from the mantissa MSBs.

module reciprocal_lut_16b (
    input  [3:0] addr,
    output reg [12:0] data
);

    always @(*) begin
        case (addr)
                4'h0: data = 13'h1000;
                4'h1: data = 13'h0f0f;
                4'h2: data = 13'h0e38;
                4'h3: data = 13'h0d79;
                4'h4: data = 13'h0ccc;
                4'h5: data = 13'h0c30;
                4'h6: data = 13'h0ba2;
                4'h7: data = 13'h0b21;
                4'h8: data = 13'h0aaa;
                4'h9: data = 13'h0a3d;
                4'ha: data = 13'h09d8;
                4'hb: data = 13'h097b;
                4'hc: data = 13'h0924;
                4'hd: data = 13'h08d3;
                4'he: data = 13'h0888;
                4'hf: data = 13'h0842;
            default: data = 13'h1000;
        endcase
    end

endmodule
